### ISSUE TITLE
Crowdloan Frontend

### ISSUE THREAD

**Issue by stechu** [Manta-Network/calamari-crowdloan-ui#2]
- [x] Your contribution
- [x] Make contribution
- [x] Leader board (connecting to subscan's API, testing the UI using on-going crowdloan) 
- [x] Referral (connecting to subscan's API) 
- [x] Analytics visualization (Good to have)
- [x] A detailed PLO/Crowdloan spec (published that in docs.manta.network) [move the medium content to docs]
- [x] Deployment 
   - [x] gh-pages - see https://crowdloan.calamari.manta.network
   - [x] "plan-B" (IPFS?) - see https://bafybeigvuzy67e5wsahjivbrf263wihellk2pjv5o2r3qahh6ewzul3ym4.ipfs.infura-ipfs.io
- [x] Landing page (calamari.manta.network)
   - [x] gh-pages - see https://calamari.manta.network
   - [x] "plan-B" (IPFS?) - see https://ipfs.infura.io/ipfs/QmXv59yDDS3xPPc17ndL69B6xrtRtUJ1bnfCfsUdguv4V3
- [x] better messaging connecting to wallet 
- [ ] Stress testing (1K contributions)
- [x] versioning (git commit hashes)
- [ ] make sure all the users can get the up to date version (don't know how to solve yet)
- [x] report issue from users (what are the information we ask from the users: front-end version, browsers, OS) (discord)

**Comment by grenade** [comment]
for aws deployment (to https://crowdloan.calamari.manta.systems/):
- i created an s3 bucket to host the static site files (the bucket name must be the same as the cname alias we create later)
  - bucket creation instructions: https://docs.aws.amazon.com/AmazonS3/latest/userguide/HostingWebsiteOnS3Setup.html
  - bucket policy instructions: https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule
  - bucket configuration: https://console.aws.amazon.com/s3/buckets/crowdloan.calamari.manta.systems
  - bucket: crowdloan.calamari.manta.systems.s3-website.eu-central-1.amazonaws.com
- i created a cloudfront distribution (in order to use tls/https)
  - cloudfront distribution creation instructions: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-creating-console.html
  - cloudfront distribution configuration https://console.aws.amazon.com/cloudfront/v3/home?#/distributions/E1CPETX30NFUTJ
- i created an acm ssl certificate for crowdloan.calamari.manta.systems (shumo will have to create validation records for manta.network) and associated it with the cloudfront distribution
- i created a cname alias at `crowdloan.calamari.manta.systems` pointing to the distribution (canonical) domain name `d321j0xqkqqp2d.cloudfront.net`
- i deployed the website using the following commands:
   ```
   git clone git@github.com:Manta-Network/calamari-crowdloan-ui.git
   cd calamari-crowdloan-ui
   yarn
   yarn install
   yarn build
   aws s3 sync ./build/ s3://crowdloan.calamari.manta.systems --delete --region eu-central-1 --profile pelagos
   ```
we can add a github action to manage the deployment using something similar to: https://dev.to/johnkevinlosito/deploy-static-website-to-s3-using-github-actions-4a0e

**Comment by grenade** [comment]
for ipfs deployment, the simplest thing to do is just:
```bash
npx ipfs-deploy build
```
which produces a deployed site like: https://bafybeigvuzy67e5wsahjivbrf263wihellk2pjv5o2r3qahh6ewzul3ym4.ipfs.infura-ipfs.io which we can point a cname at.
